### ISSUE TITLE
2 station in this same place

### ISSUE THREAD

**Issue by fab1an2** [brianshea2/meshmap.net#4]
I have trouble to select node on map. Two node is in this same place.

Meybe create a table for specyfic region? I have slow connection. I no need map. I need table of nodes
similar **meshtastic --nodes**

**Comment by brianshea2** [comment]
MeshMap is a map first and foremost. So a complete node list/table is out of scope for this project, mainly because only nodes reporting locations are currently collected.

The trouble around picking a node when multiple are on the same point is a concern.

**Comment by bialystok** [comment]
Unfortunately, not all people have high-speed Internet. I would like to be able to read how many nodes there are in my area and not download megabytes but kilobytes.

**Comment by 128element** [comment]
My internet is not slow but I must pay for traffic
;(

**Comment by brianshea2** [comment]
Untangling the mess I caused between this and #3 :)

This issue is specifically the difficulty in selecting between nodes on the same point on the map.

#3 deals with more generically showing the node lists as tables.

**Comment by brianshea2** [comment]
This issue is two in one:

1) Difficulty in selecting between nodes on the same point on the map

2) Request for per-region tables

As for 2, that request would be better suited by its own project. MeshMap is a map, and while it could offer some secondary tables, those tables would ultimately be sourced from the same data, not saving any bandwidth, and only containing nodes which are reporting position. Such tables instead would be better served by complete node lists (including neighbors of nodes reporting position), separated into regions. That is simply out of scope for this project. The program which collects the node data for the map, `meshobserv`, is freely available in this repo if someone wanted to modify it and start such a project.

Let this issue (#4) now only be relevant for the difficulty in selecting between nodes on the same point.

**Comment by brianshea2** [comment]
Closing this issue for now. I'd prefer the mapping library offer an affordance for choosing between markers at the same point. At this point in time, this is a common issue for all similar maps.
